version: '3.8'

services:
  mysql:
    build: ./my-sql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db01
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  fastapi:
    build: ./data-insert
    container_name: data_insert_container
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db01

volumes:
  db_data:
  