version: '3.8'

services:
  mysql:
    build: ./mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db01
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  data-insert:
    build: ./data-insert
    container_name: data_insert_container
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db01

  model-training:
    build: ./model-training
    container_name: model_training_container
    depends_on:
      - mysql
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db01
    volumes:
      - ./src:/app/src
      - ./model-training/app:/app/app
      - ./models:/models

  model-inference:
    build: ./model-inference
    container_name: model_inference_container
    depends_on:
      - model-training
    ports:
      - "8002:8000"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./models:/models
      - ./src:/app/src 

volumes:
  db_data:
